// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlnErp102.Data;

#nullable disable

namespace SlnErp102.Data.Migrations
{
    [DbContext(typeof(SlnDbContext))]
    [Migration("20220117140553_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SlnErp102.Core.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblCities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Istanbul",
                            Region = "Marmara"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ankara",
                            Region = "Ic Anadolu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Izmir",
                            Region = "Ege"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Antalya",
                            Region = "Akdeniz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Diyarbakir",
                            Region = "Guney Dogu Anadolu"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Samsun",
                            Region = "Karadeniz"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kars",
                            Region = "Dogu Anadolu"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblDepartments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Satin Alma",
                            Type = "H"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finans",
                            Type = "H"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ameliyathane",
                            Type = "H"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rektorluk",
                            Type = "H"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IK",
                            Type = "H"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hasta Haklari",
                            Type = "H"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Finans",
                            Type = "C"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Satin Alma",
                            Type = "C"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Depo",
                            Type = "C"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sahip",
                            Type = "C"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyTypeId");

                    b.ToTable("tblCompanies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyTypeId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(723),
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(724),
                            ModifiedUser = "system",
                            Name = "Ortek"
                        },
                        new
                        {
                            Id = 2,
                            CompanyTypeId = 2,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(725),
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(726),
                            ModifiedUser = "system",
                            Name = "Syntex"
                        },
                        new
                        {
                            Id = 3,
                            CompanyTypeId = 3,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(727),
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(727),
                            ModifiedUser = "system",
                            Name = "Kayacan"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceTitle")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId");

                    b.ToTable("tblCompanyBranches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Esenyurt",
                            CityId = 1,
                            CompanyId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(528),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(528),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Izmir",
                            CityId = 2,
                            CompanyId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(531),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(531),
                            ModifiedUser = "system",
                            Name = "Izmir Sube"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ankara",
                            CityId = 3,
                            CompanyId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(532),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(533),
                            ModifiedUser = "system",
                            Name = "Ankara Sube"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Esenyurt",
                            CityId = 1,
                            CompanyId = 2,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(534),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(534),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Izmir",
                            CityId = 2,
                            CompanyId = 2,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(536),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(536),
                            ModifiedUser = "system",
                            Name = "Izmir Sube"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Ankara",
                            CityId = 3,
                            CompanyId = 2,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(537),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(538),
                            ModifiedUser = "system",
                            Name = "Ankara Sube"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gsm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Officer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("tblCompanyDetails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DepartmentId = 7,
                            Email = "111@gmail.com",
                            Fax = "111",
                            Gsm = "111",
                            Officer = "Sinan",
                            Phone = "111"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            DepartmentId = 8,
                            Email = "222@gmail.com",
                            Fax = "222",
                            Gsm = "222",
                            Officer = "Sukran",
                            Phone = "222"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            DepartmentId = 9,
                            Email = "333@gmail.com",
                            Fax = "333",
                            Gsm = "333",
                            Officer = "Turgay",
                            Phone = "333"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            DepartmentId = 10,
                            Email = "444@gmail.com",
                            Fax = "444",
                            Gsm = "444",
                            Officer = "Tahir",
                            Phone = "444"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblCompanyTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Musteri"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tedarikci"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ana Satici"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Distributor"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Doctors.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("date");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ClinicAddress")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("tblDoctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(789),
                            CityId = 1,
                            ClinicAddress = "Fulya/Besiktas",
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(790),
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(791),
                            ModifiedUser = "system",
                            Name = "Omer Taser",
                            Title = 0
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(792),
                            CityId = 1,
                            ClinicAddress = "Tesvikiye/Sisli",
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(793),
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(793),
                            ModifiedUser = "system",
                            Name = "Mehmet Demirhan",
                            Title = 0
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(794),
                            CityId = 1,
                            ClinicAddress = "Abide-i Hürriyet Cd No:166, 34381 Şişli/İstanbul",
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(795),
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(795),
                            ModifiedUser = "system",
                            Name = "Azmi Hamzaoglu",
                            Title = 0
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Doctors.DoctorDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gsm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("HospitalId");

                    b.ToTable("tblDoctorDetails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            Email = "taser@gmail.com",
                            Fax = "111",
                            Gsm = "111",
                            HospitalId = 1,
                            Phone = "111"
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 2,
                            Email = "demirhan@gmail.com",
                            Fax = "222",
                            Gsm = "222",
                            HospitalId = 3,
                            Phone = "222"
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 3,
                            Email = "hamzaoglu@gmail.com",
                            Fax = "333",
                            Gsm = "333",
                            HospitalId = 2,
                            Phone = "333"
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 3,
                            Email = "",
                            Fax = "",
                            Gsm = "",
                            HospitalId = 6,
                            Phone = "444"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("date");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("WorkEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("WorkStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("tblEmployees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(916),
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(917),
                            Description = "Aciklama1",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(917),
                            ModifiedUser = "system",
                            Name = "Serdar",
                            Picture = "user1.png",
                            WorkEnd = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(915),
                            WorkStart = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(914)
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(920),
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(921),
                            Description = "Aciklama2",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(922),
                            ModifiedUser = "system",
                            Name = "Recep",
                            Picture = "user2.png",
                            WorkEnd = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(919),
                            WorkStart = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(919)
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(924),
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(924),
                            Description = "Aciklama3",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(925),
                            ModifiedUser = "system",
                            Name = "Melek",
                            Picture = "user3.png",
                            WorkEnd = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(923),
                            WorkStart = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(923)
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Employees.EmployeeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gsm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("tblEmployeeDetails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "111@gmail.com",
                            EmployeeId = 1,
                            Fax = "234",
                            Gsm = "1234",
                            Phone = "1234"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "222@gmail.com",
                            EmployeeId = 2,
                            Fax = "234",
                            Gsm = "1234",
                            Phone = "1234"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "333@gmail.com",
                            EmployeeId = 3,
                            Fax = "234",
                            Gsm = "1234",
                            Phone = "1234"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("HospitalTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalTypeId");

                    b.ToTable("tblHospitals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(220),
                            HospitalName = "AciBadem",
                            HospitalTypeId = 1,
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(206),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(223),
                            HospitalName = "Florence Nightingale",
                            HospitalTypeId = 1,
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(222),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(224),
                            HospitalName = "Medicana",
                            HospitalTypeId = 1,
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(224),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(226),
                            HospitalName = "Beylikduzu Devlet",
                            HospitalTypeId = 2,
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(225),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(227),
                            HospitalName = "KANUNİ SULTAN SÜLEYMAN",
                            HospitalTypeId = 9,
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(226),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(228),
                            HospitalName = "Cam ve Sakura",
                            HospitalTypeId = 3,
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(228),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(230),
                            HospitalName = "Kocaeli Üniversitesi Hastanesi",
                            HospitalTypeId = 4,
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(229),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(231),
                            HospitalName = "Gata",
                            HospitalTypeId = 6,
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(231),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(233),
                            HospitalName = "Bezmialem Vakıf Üni. Tıp Fakültesi Hastanesi",
                            HospitalTypeId = 7,
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(232),
                            ModifiedUser = "system"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("HospitalId");

                    b.ToTable("tblHospitalBranches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Acibadem/Kadikoy",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(451),
                            HospitalId = 1,
                            InvoiceTitle = "Acibadem Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(452),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Çankaya/Ankara",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(454),
                            HospitalId = 1,
                            InvoiceTitle = "Acibadem Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(455),
                            ModifiedUser = "system",
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Tepebaşı/Eskişehir",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(456),
                            HospitalId = 1,
                            InvoiceTitle = "Acibadem Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(457),
                            ModifiedUser = "system",
                            Name = "Eskisehir"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Şişli/İstanbul",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(458),
                            HospitalId = 2,
                            InvoiceTitle = "Florence Nightingale Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(458),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Beylikdüzü/İstanbul",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(460),
                            HospitalId = 3,
                            InvoiceTitle = "Medikana Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(460),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Beylikdüzü/İstanbul",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(461),
                            HospitalId = 4,
                            InvoiceTitle = "Devlet Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(462),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Gazi Osman Pasa/İstanbul",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(463),
                            HospitalId = 5,
                            InvoiceTitle = "Devlet Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(463),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Basaksehir/İstanbul",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(464),
                            HospitalId = 6,
                            InvoiceTitle = "Devlet Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 17, 17, 5, 52, 950, DateTimeKind.Local).AddTicks(465),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gsm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HospitalBranchId")
                        .HasColumnType("int");

                    b.Property<string>("Officer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("HospitalBranchId");

                    b.ToTable("tblHospitalDetails", (string)null);
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblHospitalTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ozel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Devlet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sehir"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Universite"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vakif"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Askeri"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sb"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Klinik"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Arastirma"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.Company", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Infos.Companies.CompanyType", "CompanyType")
                        .WithMany("Companies")
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyType");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyBranch", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.City", "City")
                        .WithMany("CompanyBranches")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Infos.Companies.Company", "Company")
                        .WithMany("CompanyBranches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyDetail", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Infos.Companies.Company", "Company")
                        .WithMany("CompanyDetails")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Department", "Department")
                        .WithMany("CompanyDetails")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Doctors.Doctor", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.City", "City")
                        .WithMany("Doctors")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Doctors.DoctorDetail", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Infos.Doctors.Doctor", "Doctor")
                        .WithMany("DoctorDetails")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Infos.Hospitals.Hospital", "Hospital")
                        .WithMany("DoctorDetails")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Employees.Employee", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.City", "City")
                        .WithMany("Employees")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Employees.EmployeeDetail", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Department", "Department")
                        .WithMany("EmployeeDetails")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Infos.Employees.Employee", "Employee")
                        .WithMany("EmployeeDetails")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.Hospital", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Infos.Hospitals.HospitalType", "HospitalType")
                        .WithMany("Hospitals")
                        .HasForeignKey("HospitalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HospitalType");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalBranch", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.City", "City")
                        .WithMany("HospitalBranches")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Infos.Hospitals.Hospital", "Hospital")
                        .WithMany("HospitalBranch")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalDetail", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Department", "Department")
                        .WithMany("HospitalDetails")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Infos.Hospitals.HospitalBranch", "HospitalBranches")
                        .WithMany("HospitalDetails")
                        .HasForeignKey("HospitalBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("HospitalBranches");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.City", b =>
                {
                    b.Navigation("CompanyBranches");

                    b.Navigation("Doctors");

                    b.Navigation("Employees");

                    b.Navigation("HospitalBranches");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Department", b =>
                {
                    b.Navigation("CompanyDetails");

                    b.Navigation("EmployeeDetails");

                    b.Navigation("HospitalDetails");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.Company", b =>
                {
                    b.Navigation("CompanyBranches");

                    b.Navigation("CompanyDetails");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyType", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Doctors.Doctor", b =>
                {
                    b.Navigation("DoctorDetails");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Employees.Employee", b =>
                {
                    b.Navigation("EmployeeDetails");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.Hospital", b =>
                {
                    b.Navigation("DoctorDetails");

                    b.Navigation("HospitalBranch");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalBranch", b =>
                {
                    b.Navigation("HospitalDetails");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalType", b =>
                {
                    b.Navigation("Hospitals");
                });
#pragma warning restore 612, 618
        }
    }
}
